<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>C44_G01_MVC04.BLL</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\C44-G01-MVC04.DAL\C44-G01-MVC04.DAL.csproj" />
  </ItemGroup>

</Project>
